# Generated by Django 2.2.1 on 2021-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210406_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_interior',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
